services:
  app-db:
    image: postgres:16
    container_name: evote-app-db
    environment:
      POSTGRES_DB: evote
      POSTGRES_USER: evote
      POSTGRES_PASSWORD: evote123
    ports:
      - "5432:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evote -d evote"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - evote-net



  merkle-service:
    build: ./home/riad/e-voting-blockchain-system/merkle-service
    container_name: merkle-service
    environment:
      - CHAIN_ID=31337
      - PORT=4000
      - RPC_URL=http://host.docker.internal/8545
      - DATABA_URL=postgresql://evote:evote123@app-db:5432/evote
    ports:
      - "4000:4000"
    depends_on:
      app-db:
        condition: service_healthy
    networks:
      - evote-net


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak 
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: evote123
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    ports:
      - "8082:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    volumes:
      - ./themes:/opt/keycloak/themes
      - ./providers:/opt/keycloak/providers
    networks:
      - evote-net


  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: evote123
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - evote-net

volumes:
  app_db_data:
  keycloak_db_data: 

networks:
  evote-net:
    external: true

